spring:
  application:
    name: rentsure-backend
  profiles:
    active: dev
  jackson:
    default-property-inclusion: non_null

server:
  port: 8080

app:
  jwt:
    secret: ${JWT_SECRET:vErYsEcReTjWtKeYtHaTiSaTlEaSt256BiTsLoNg}
    access-token-expiration-minutes: 15
    refresh-token-expiration-days: 7
